---
title: "12_one_factor_ANOVA"
author: "Nick Schultz"
date: "3/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
dmx <- tibble(sub_id = 1:9,
              i = rep(1:3, each = 3),
              j  = rep(1:3, times = 3),
              typos = c(111, 102, 111, 89, 127, 90, 97, 85, 88),
              sound = rep(c("cafe", "jazz", "silence"), each = 3)) %>%
  mutate(mu = mean(typos)) %>%
  group_by(i) %>%
  mutate(Ai = mean(typos) - mu) %>%
  ungroup() %>%
  mutate(err = typos - (mu + Ai))
```

```{r}
dat_ss <- dmx %>%
  summarise(total = sum(typos^2),
            ss_mu = sum(mu^2),
            ss_sound = sum(Ai^2),
            ss_err = sum(err^2))

ms_a <- dat_ss[["ss_sound"]] /2L

ms_err <- dat_ss[["ss_err"]] / 6L

f_obs <- ms_a / ms_err

pf(f_obs, 2, 6, lower.tail = FALSE)
```

```{r}
library(afex)

dat <- select(dmx, sub_id, typos, sound)

results <- afex::aov_ez(data = dat,
                        dv = "typos",
                        id = "sub_id",
                        type = 3,
                        between = "sound")

print(results$anova_table)
```

